project_id = "wmfkcchajdcehvjomfdr"

[functions.create-admin-payment]
verify_jwt = false

[functions.verify-admin-payment]
verify_jwt = false

[functions.create-dev-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false