// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmfkcchajdcehvjomfdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtZmtjY2hhamRjZWh2am9tZmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjM5OTUsImV4cCI6MjA3MjM5OTk5NX0.WM0YrD0ZZKyIpufLDA-gYBuxIWcT7S5w1HCE02dkH00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});